### PR TITLE
Use unprivileged nginx docker image

### PR DESCRIPTION
**Pull request by thomas-illiet**

### CODE REVIEW

**Comment by farapholch** [comment]
Just tested this. Seems to be working fine, will be testing more next week.

**Comment by alswl** [comment]
Thanks for your pull-request, and I'm so sorry for late response.

I will change your target branch to `feat/v0.17.0-env-dynamic-in-docker-container`, this the the feature for dynamic loading by nginx. The `fork` branch is just a pointer the latest forked release.

Update:

Change the target cause more changes than desired, Maybe cherry-pick is required.

**Comment by alswl** [comment]
```
 > [stage-1 3/7] RUN apk update && apk add sed bash python3 py3-pip:
0.338 ERROR: Unable to lock database: Permission denied
0.338 ERROR: Failed to open apk database: Permission denied
```

error is occurred.

**Comment by farapholch** [comment]
> ```
>  > [stage-1 3/7] RUN apk update && apk add sed bash python3 py3-pip:
> 0.338 ERROR: Unable to lock database: Permission denied
> 0.338 ERROR: Failed to open apk database: Permission denied
> ```
> 
> error is occurred.

IF i added "USER root" just before the Command it worked.

**Comment by alswl** [comment]
@thomas-illiet @farapholch 
I checked the changes and this makes difference behavior of upstream:

1. internal port listen
2. expose port

I want follow with the upstream Dockerfile, keep the minimal changes. Maybe you need make another Dockerfile to use unprivileged.

**Comment by farapholch** [comment]
@alswl This sound perfectly fine. I'll have a separe dockerfile for unpriviliged, thanks!

**Pull request closed without merging**
